[http_streamer]
url = "https://192.168.1.144:5000"
cert = "/home/pi/cert/kovalenko.crt"
key = "/home/pi/cert/kovalenko.key"

[inputs]
items = [ 
    { id = "video1", type = "WebCamera", url = "/dev/video1", hw_name = "", hw_id = 0 }
]